using System.Collections.Generic;

namespace Change.Editor.PSD2UI
{
    /// <summary>
    /// Generates the C# source code string for a view from scanned component info.
    /// (Minimal stub — full implementation in task 21.)
    /// </summary>
    public class ViewCodeTemplate
    {
        /// <summary>
        /// Generates the view code string for the given prefab and its interactive components.
        /// </summary>
        /// <param name="prefabName">The prefab name (e.g., "QuestWindow").</param>
        /// <param name="moduleName">The extracted module name (e.g., "Quest").</param>
        /// <param name="components">The scanned interactive components.</param>
        /// <returns>The generated C# source code as a string.</returns>
        public string Generate(string prefabName, string moduleName, List<ComponentInfo> components)
        {
            // TODO (task 21): Implement full template-based code generation.
            // This placeholder produces a valid skeleton so the pipeline compiles.
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// Auto-generated by PSD2UI. Do not edit manually.");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine("using TMPro;");
            sb.AppendLine();
            sb.AppendLine($"namespace Change.Runtime.UI.{moduleName}.Views.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {prefabName}View");
            sb.AppendLine("    {");

            // Field bindings
            if (components != null && components.Count > 0)
            {
                sb.AppendLine("        // Bindings");
                foreach (var comp in components)
                {
                    sb.AppendLine($"        public {comp.Type} {comp.Name};");
                }

                sb.AppendLine();
                sb.AppendLine("        // Event registration");
                sb.AppendLine("        public void RegisterEvents()");
                sb.AppendLine("        {");
                foreach (var comp in components)
                {
                    sb.AppendLine($"            {comp.Name}.{comp.EventType}.AddListener(On{comp.Name}Changed);");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        // Event handlers (to be implemented by partial class)");
                foreach (var comp in components)
                {
                    sb.AppendLine($"        partial void On{comp.Name}Changed();");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
